name: aflsdfjsd
my:
  number: ${random.int(20)}
  name:
    - chenyouhuang1
    - chenyouhuang2
    - chenyouhuang3
  
my.profile: default

server:
  port: 9090
  
spring:
  redis:
    host: 58.215.180.219

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: youhuang
    driver-class-name: com.mysql.jdbc.Driver
    
    primary:
      url: jdbc:mysql://127.0.0.1:3306/test
      username: root
      password: youhuang
      driver-class-name: com.mysql.jdbc.Driver    
    secondary:
      url: jdbc:mysql://127.0.0.1:3306/shop
      username: root
      password: youhuang
      driver-class-name: com.mysql.jdbc.Driver  
    
  aop:
    proxy-target-class: false

---
spring:
  profiles: dev
  
my:
  profile: dev
  
---
spring:
  profiles: test
  
my:
  profile: test
  
---
spring:
  profiles: release
  
my:
  profile: release  
  