name: aflsdfjsd
my:
  number: ${random.int(20)}
  name:
    - chenyouhuang1
    - chenyouhuang2
    - chenyouhuang3
  
my.profile: default

server:
  port: 9090
  
spring:
  redis:
    host: 58.215.180.219
  
---
spring:
  profiles: dev
  
my:
  profile: dev
  
---
spring:
  profiles: test
  
my:
  profile: test
  
---
spring:
  profiles: release
  
my:
  profile: release  
  